Various improvements
shakacode/heroku-to-control-plane pull request #146
Opened 2024-03-20 21:30 UTC by rafaelgomesxyz

- Adds comments regarding `app_workloads` and `additional_workloads`, to improve documentation
- Changes template substitution to use double braces (e.g., `APP_ORG` -> `{{APP_ORG}}`) (backwards compatible)
- Renames template substitution variable `APP_GVC` to `{{APP_NAME}}` (backwards compatible)
- Adds new template substitution variables: `{{APP_LOCATION_LINK}}`, `{{APP_IMAGE_LINK}}`, `{{APP_IDENTITY}}`, `{{APP_IDENTITY_LINK}}`, `{{APP_SECRETS}}` and `{{APP_SECRETS_POLICY}}`
- Changes `setup-app` command to automatically bind the app to the secrets policy, as long as both the identity and the policy exist
- Adds `--skip-secret-access-binding` option to `setup-app` command to prevent behavior above
- Adds `--run-release-phase` option to `deploy-image` command to run release script before deploying (same step as in `promote-app-from-upstream` command)
- Refreshes local API token when it is about to expire
- Changes `apply-template` command to exit with non-zero code if failed to apply any templates

2024-03-20 21:37 UTC, rafaelgomesxyz commented on cpl.gemspec
> +  spec.add_dependency "jwt",      "~> 2.8.1"
Need `jwt` to decode the token and check the `exp` date.

2024-03-20 21:37 UTC, rafaelgomesxyz commented on lib/command/base.rb
> +    def perform!(cmd)
Just for consistency. We generally add `!` at the end of the method name if it raises an error.

2024-03-20 21:37 UTC, rafaelgomesxyz commented on lib/command/cleanup_stale_apps.rb
> -require "date"
Moved to `cpl.rb` so we require everything in one place.

2024-03-20 21:37 UTC, rafaelgomesxyz commented on lib/command/promote_app_from_upstream.rb
> -    def check_release_script
Moved to `deploy-image` command.

2024-03-20 23:08 UTC, justin808 commented
> Changes setup-app command to automatically bind the app to the secrets policy, as long as both the identity and the policy exist

If not existing, we should show a message that can be ignored with the option to skip

2024-03-20 23:18 UTC, justin808 commented
> Adds --run-release-phase option to deploy-image command to run release script before deploying (same step as in promote-app-from-upstream command)

Follow-up PR: 

1. Make the default behavior
2. V2 of the gem b/c breaking change b/c `--run-release-phase` is default for `deploy-image`, so need to document the upgrade if somebody doesn't want it. And also log a message if the release_phase script is not defined. This message only shows unless `--run-release-phase=false`

2024-03-20 23:50 UTC, justin808 requested changes

2024-03-20 23:50 UTC, justin808 commented on README.md
>      setup_app_templates:
```
# Note:
# 1. These names correspond to files in the ./controlplane/templates directory.
# 2. Each file can contain many objects, such as in the case of the templates that create a resource, like postgres
# 3. While the naming often corresponds to a workload or other object name, the naming is arbitrary. 
#     Naming does not need to match anything other than the file name without the .yml extension.
```

2024-03-20 23:50 UTC, justin808 commented on README.md
>      app_workloads:
```
# On the other hand, if you have a workload for Redis, that would NOT use the application Docker image and
# not be listed here.
```

2024-03-20 23:50 UTC, justin808 commented on docs/commands.md
> +{{APP_LOCATION}}      - default location
```
{{APP_LOCATION}} - location, per YML file, ENV, or command line arg
```

2024-03-20 23:50 UTC, justin808 commented on docs/commands.md
> +{{APP_LOCATION_LINK}} - full link for default location, ready to be used in `staticPlacement.locationLinks`
```
{{APP_LOCATION_LINK}} - full link for location, ready to be used for the value of `staticPlacement.locationLinks` in templates
```

2024-03-20 23:50 UTC, justin808 commented on docs/commands.md
> +{{APP_IDENTITY_LINK}} - full link for default identity, ready to be used in `identityLink`
```
{{APP_IDENTITY_LINK}} - full link for the value ready to be used in `identityLink` in the templates
```

2024-03-20 23:50 UTC, justin808 commented on docs/commands.md
> +- The deploy will fail if the release script exits with a non-zero code
or the release script doesn't exist

2024-03-20 23:50 UTC, justin808 commented on examples/controlplane.yml
> +    setup_app_templates:
grab additional comments from readme

2024-03-20 23:50 UTC, justin808 commented on lib/command/apply_template.rb
> +      {{APP_IDENTITY_LINK}} - full link for default identity, ready to be used in `identityLink`
see comments above for naming

2024-03-20 23:50 UTC, justin808 commented on lib/command/apply_template.rb
> +                 # Kept for backwards compatibility
Warn if old ones exist and suggest renaming as support for them will be removed in a future major version bump.

2024-03-20 23:50 UTC, justin808 commented on lib/command/base.rb
>        system(cmd) || exit(false)
```rb
exit(1)
```

2024-03-20 23:50 UTC, justin808 commented on lib/command/promote_app_from_upstream.rb
> +        - If `release_script` is specified in the `.controlplane/controlplane.yml` file, passes `--run-release-phase` to `cpl deploy-image`
```
    - Runs `cpl deploy-image` to deploy the image. If `.controlplane/controlplane.yml` includes the
      `release_script`, `cpl deploy-image` will use the `--run-release-phase` option.
```

2024-03-20 23:50 UTC, justin808 commented on lib/command/setup_app.rb
> +                cp.fetch_identity(app_identity).nil? ||
would rather have an error and not silently skip

2024-03-20 23:50 UTC, justin808 commented on lib/core/controlplane.rb
> +    cmd += "> /dev/null 2>&1"
Please check code base for this pattern.

It swallows all error messages!

2024-03-21 03:27 UTC, justin808 approved these changes

2024-03-21 03:27 UTC, merged