Add run:cleanup command
shakacode/heroku-to-control-plane pull request #45
Opened 2023-05-11 18:38 UTC by rafaelgomesxyz

![Code_KKUSAscquk](https://github.com/shakacode/heroku-to-control-plane/assets/25509361/d372cd28-e7bb-48fd-a318-35118a00d5b2)

2023-05-15 06:47 UTC, justin808 commented on docs/commands.md
> +- Will ask for explicit user confirmation
is this what you mean?
> Will ask for explicit user confirmation of deletion.

2023-05-15 06:49 UTC, justin808 commented on lib/command/run_cleanup.rb
> +      - Specify the amount of days after a run workload should be considered stale through `stale_run_workload_created_days` in the `.controlplane/controlplane.yml` file
see above comment regarding wording of this param

2023-05-15 06:51 UTC, justin808 commented on lib/command/run_cleanup.rb
> +        end
can we have specs for this method?

2023-05-15 06:52 UTC, justin808 commented on lib/command/run_cleanup.rb
> +        progress.puts("  #{workload[:name]} (#{Shell.color((workload[:date]).to_s, :red)})")
Can you list how many days ago?

2023-05-15 06:54 UTC, justin808 commented on lib/command/run_cleanup.rb
> +            diff_in_days = (now - created_date).to_i
Are you 100% Ruby returns the difference in date **time** in terms of **days**?

2023-05-15 06:55 UTC, justin808 commented on lib/command/run_cleanup.rb
> +            next unless diff_in_days >= stale_run_workload_created_days
Do we need to worry about any rounding errors?

2023-05-15 06:55 UTC, justin808 requested changes
See comments

2023-05-17 17:46 UTC, rafaelgomesxyz commented on lib/command/run_cleanup.rb
> +        end
Done.

2023-05-19 05:27 UTC, justin808 approved these changes

2023-05-19 05:27 UTC, justin808 approved these changes

2023-05-19 05:28 UTC, merged